Affine Function

In [11]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

x = tf.constant([[10.], [20.]])

dense = Dense(units=1, activation='linear')

y_tf = dense(x) # forward propagation + params initialization

W, B = dense.get_weights()

y_man = tf.linalg.matmul(x, W) + B

print('===========')
print("x: {} ->\n {} \n".format(x.shape, x.numpy()))
print("W: {} ->\n {} \n".format(W.shape, W))
print("B: {} ->\n {} \n".format(B.shape, B))

print('===========')
print("y(Tensorflow): {}\n{}\n".format(y_tf.shape, y_tf.numpy()))
print("y(Matmul): {}\n{}\n".format(y_man.shape, y_man.numpy()))

x: (2, 1) ->
 [[10.]
 [20.]] 

W: (1, 1) ->
 [[1.107634]] 

B: (1,) ->
 [0.] 

y(Tensorflow): (2, 1)
[[11.07634]
 [22.15268]]

y(Matmul): (2, 1)
[[11.07634]
 [22.15268]]



Parameters Initialization

In [13]:
import tensorflow as tf

from tensorflow.keras.layers import Dense
from tensorflow.keras.initializers import Constant

w, b = tf.constant(10.), tf.constant(20.)
w_init, b_init = Constant(w), Constant(b)

dense = Dense(units=1,
              activation='linear',
              kernel_initializer=w_init,
              bias_initializer=b_init)

y_tf = dense(x)

W, B = dense.get_weights()

print('===========')
print("x: {} ->\n {} \n".format(x.shape, x.numpy()))
print("W: {} ->\n {} \n".format(W.shape, W))
print("B: {} ->\n {} \n".format(B.shape, B))

x: (2, 1) ->
 [[10.]
 [20.]] 

W: (1, 1) ->
 [[10.]] 

B: (1,) ->
 [20.] 



Affine Functions with n Features

In [15]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

x = tf.random.uniform(shape=(1, 10), minval=0, maxval=10)

dense = Dense(units=1)

y_tf = dense(x)

W, B = dense.get_weights()

y_man = tf.linalg.matmul(x, W) + B

print('===========')
print("x: {} ->\n {} \n".format(x.shape, x.numpy()))
print("W: {} ->\n {} \n".format(W.shape, W))
print("B: {} ->\n {} \n".format(B.shape, B))

print('===========')
print("y(Tensorflow): {}\n{}\n".format(y_tf.shape, y_tf.numpy()))
print("y(Matmul): {}\n{}\n".format(y_man.shape, y_man.numpy()))

x: (1, 10) ->
 [[6.7232    5.557699  0.6475985 5.770185  5.145085  9.475393  3.670758
  2.4802148 9.612785  9.465593 ]] 

W: (10, 1) ->
 [[-0.12121451]
 [ 0.5207775 ]
 [-0.6980227 ]
 [-0.0099799 ]
 [ 0.07008135]
 [-0.05502248]
 [ 0.71154934]
 [ 0.33065838]
 [-0.30202666]
 [ 0.05364513]] 

B: (1,) ->
 [0.] 

y(Tensorflow): (1, 1)
[[2.4454608]]

y(Matmul): (1, 1)
[[2.4454608]]

