### Dense Layers

Shapes of Dense Layers

In [2]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

N, n_feature = 8, 10
X = tf.random.normal(shape=(N, n_feature))

n_neuron = 3
dense = Dense(units=n_neuron, activation='sigmoid')
Y = dense(X)

W, B = dense.get_weights()

print('======================')
print("X: ", X.shape)
print("W: ", W.shape)
print("B: ", B.shape)
print("Y: ", Y.shape)

X:  (8, 10)
W:  (10, 3)
B:  (3,)
Y:  (8, 3)


Calculation

In [9]:
import numpy as np
import tensorflow as tf

from tensorflow.math import exp
from tensorflow.linalg import matmul

from tensorflow.keras.layers import Dense

N, n_feature = 4, 10
X = tf.random.normal(shape=(N, n_feature))

n_neuron = 3
dense = Dense(units=n_neuron, activation='sigmoid')
Y_tf = dense(X)

W, B = dense.get_weights()
print("Y(Tensorflow): \n", Y_tf.numpy())

Z = matmul(X, W) + B
Y_man_matmul = 1 / (1 + exp(-Z))
print("Y(with matrix multiplication: \n", Y_man_matmul.numpy())

# dot product
Y_man_vec = np.zeros(shape=(N, n_neuron))
for x_idx in range(N):
  x = X[x_idx]

  for nu_idx in range(n_neuron):
    w, b = W[:, nu_idx], B[nu_idx]

    z = tf.reduce_sum(x * w) + b
    a = 1/(1 + np.exp(-z))
    Y_man_vec[x_idx, nu_idx] = a

print("Y(with dot products): \n", Y_man_vec)

Y(Tensorflow): 
 [[0.5784518  0.72433925 0.377539  ]
 [0.16027576 0.83551407 0.90179217]
 [0.24797311 0.35391504 0.36988705]
 [0.4280033  0.57778275 0.83454084]]
Y(with matrix multiplication: 
 [[0.5784519  0.7243393  0.37753898]
 [0.16027579 0.83551407 0.90179217]
 [0.24797308 0.35391504 0.36988705]
 [0.4280033  0.57778275 0.8345409 ]]
Y(with dot products): 
 [[0.57845186 0.72433925 0.37753898]
 [0.16027579 0.83551409 0.90179219]
 [0.24797305 0.35391501 0.36988704]
 [0.42800331 0.57778278 0.83454089]]


### Cascaded Dense Layers

Shapes of Cascaded Dense Layers

In [12]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

N, n_feature = 4, 10
X = tf.random.normal(shape=(N, n_feature))

n_neurons = (3, 5)
dense1 = Dense(units=n_neurons[0], activation='sigmoid')
dense2 = Dense(units=n_neurons[1], activation='sigmoid')

A1 = dense1(X)
Y = dense2(A1)

W1, B1 = dense1.get_weights()
W2, B2 = dense2.get_weights()


print("X: {}\n".format(X.shape))

print("W1: ", W1.shape)
print("B1: ", B1.shape)
print("A1: {}\n".format(A1.shape))

print("W2: ", W2.shape)
print("B2: ", B2.shape)
print("Y: {}\n".format(Y.shape))

X: (4, 10)

W1:  (10, 3)
B1:  (3,)
A1: (4, 3)

W2:  (3, 5)
B2:  (5,)
Y: (4, 5)



Dense Layers with Python List

In [14]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

N, n_feature = 4, 10
X = tf.random.normal(shape=(N, n_feature))

n_neurons = [10, 20, 30, 40]

dense_layers = list()
for n_neuron in n_neurons:
  dense = Dense(units=n_neuron, activation='relu')
  dense_layers.append(dense)

print("Input: ", X.shape)
for dense_idx, dense in enumerate(dense_layers):
  X = dense(X)
  print("After dense layer ", dense_idx + 1)
  print(X.shape)

Input:  (4, 10)
After dense layer  1
(4, 10)
After dense layer  2
(4, 20)
After dense layer  3
(4, 30)
After dense layer  4
(4, 40)


Output 

In [16]:
import tensorflow as tf

from tensorflow.math import exp
from tensorflow.linalg import matmul
from tensorflow.keras.layers import Dense

N, n_feature = 4, 10
X = tf.random.normal(shape=(N, n_feature))
X_cp = tf.identity(X)

n_neurons = [10, 20, 30, 40]

dense_layers = list()
for n_neuron in n_neurons:
  dense = Dense(units=n_neuron, activation='sigmoid')
  dense_layers.append(dense)

print("Input: ", X.shape)
W, B = list(), list()
for dense_idx, dense in enumerate(dense_layers):
  X = dense(X)
  w, b = dense.get_weights()

  W.append(w)
  B.append(b)
print("Y(Tensorflow): \n", X.numpy())

for layer_idx in range(len(n_neurons)):
  w, b = W[layer_idx], B[layer_idx]

  X_cp = matmul(X_cp, w) + b
  X_cp = 1/(1 + exp(-X_cp))
print("Y(Manual): \n", X_cp.numpy())
  

Input:  (4, 10)
Y(Tensorflow): 
 [[0.44352597 0.45499492 0.3942266  0.52089745 0.57572144 0.40692788
  0.53828263 0.4884545  0.55251884 0.5413941  0.21682218 0.249571
  0.37931544 0.52255005 0.5798491  0.63713855 0.3363046  0.5585452
  0.5524795  0.6677488  0.38821274 0.3678243  0.49819285 0.38521326
  0.46751624 0.32561356 0.38134378 0.4140711  0.43932244 0.34939677
  0.6103392  0.47480214 0.46267134 0.40070432 0.47640336 0.33497575
  0.64610195 0.62067723 0.65816015 0.5627639 ]
 [0.4443699  0.45646194 0.39684454 0.52189785 0.5763557  0.40712523
  0.53853774 0.4902177  0.55416435 0.54252464 0.21633413 0.2509538
  0.3815214  0.52392197 0.58067024 0.6363623  0.33647627 0.55990046
  0.5537112  0.6663436  0.38793847 0.36944795 0.49612167 0.38516927
  0.46899274 0.32575867 0.38594913 0.41613698 0.43681923 0.351642
  0.6113871  0.47502846 0.46554297 0.40225837 0.4746237  0.33399135
  0.6474723  0.6201634  0.66015923 0.56267715]
 [0.44308212 0.4552146  0.39887387 0.52262145 0.5809182  0.4122