Activation Layers

In [5]:
import tensorflow as tf

from tensorflow.math import exp, maximum
from tensorflow.keras.layers import Activation

x = tf.random.normal(shape=(1, 5))

sigmoid = Activation('sigmoid')
tanh = Activation('tanh')
relu = Activation('relu')

# Use tensorflow
y_sigmoid_tf = sigmoid(x)
y_tanh_tf = tanh(x)
y_relu_tf = relu(x)

# imp. 
y_sigmoid_man = 1 / (1 + exp(-x))
y_tanh_man = (exp(x) - exp(-x)) / (exp(x) + exp(-x))
y_relu_man = maximum(x, 0)



print("x: {}\n{}\n".format(x.shape, x.numpy()))
print("Sigmoid(Tensorflow): {}\n{}".format(y_sigmoid_tf.shape, y_sigmoid_tf.numpy()))
print("Sigmoid(Manual): {}\n{}\n".format(y_sigmoid_man.shape, y_sigmoid_man.numpy()))

print("Tanh(Tensorflow): {}\n{}".format(y_tanh_tf.shape, y_tanh_tf.numpy()))
print("Tanh(Manual): {}\n{}\n".format(y_tanh_man.shape, y_tanh_man.numpy()))

print("Relu(Tensorflow): {}\n{}".format(y_relu_tf.shape, y_relu_tf.numpy()))
print("Relu(Manual): {}\n{}\n".format(y_relu_man.shape, y_relu_man.numpy()))


x: (1, 5)
[[-0.94337314  1.4638649   1.3207116  -1.2580746   2.1358297 ]]

Sigmoid(Tensorflow): (1, 5)
[[0.2802195  0.81212306 0.7893001  0.22130549 0.8943372 ]]
Sigmoid(Manual): (1, 5)
[[0.2802195 0.8121231 0.7893001 0.2213055 0.8943372]]

Tanh(Tensorflow): (1, 5)
[[-0.7367682   0.89840066  0.86696076 -0.8505325   0.9724671 ]]
Tanh(Manual): (1, 5)
[[-0.7367681   0.89840066  0.86696076 -0.8505325   0.972467  ]]

Relu(Tensorflow): (1, 5)
[[0.        1.4638649 1.3207116 0.        2.1358297]]
Relu(Manual): (1, 5)
[[0.        1.4638649 1.3207116 0.        2.1358297]]



Activation in Dense Layer

In [8]:
import tensorflow as tf

from tensorflow.math import exp
from tensorflow.keras.layers import Dense

x = tf.random.normal(shape=(1, 5))

dense_sigmoid = Dense(units=1, activation='sigmoid')
dense_tanh = Dense(units=1, activation='tanh')
dense_relu = Dense(units=1, activation='relu')

y_sigmoid = dense_sigmoid(x)
y_tanh = dense_tanh(x)
y_relu = dense_relu(x)

print("Dense with Sigmoid: {}\n{}".format(y_sigmoid.shape, y_sigmoid.numpy()))
print("Dense with Tanh: {}\n{}".format(y_tanh.shape, y_tanh.numpy()))
print("Dense with Relu: {}\n{}".format(y_relu.shape, y_relu.numpy()))

# Verification
print('\n=============\n')

W, B = dense_sigmoid.get_weights()
z = tf.linalg.matmul(x, W) + B
a = 1 / (1 + exp(-z))
print("Activation value(Tensorflow): {}\n{}".format(y_sigmoid.shape, y_sigmoid.numpy()))
print("Activation value(Manual): {}\n{}".format(a.shape, a.numpy()))

Dense with Sigmoid: (1, 1)
[[0.3281554]]
Dense with Tanh: (1, 1)
[[-0.07757642]]
Dense with Relu: (1, 1)
[[1.077647]]


Activation value(Tensorflow): (1, 1)
[[0.3281554]]
Activation value(Manual): (1, 1)
[[0.32815537]]


Artificial Neurons

In [11]:
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.math import exp, maximum

# activation = 'sigmoid'
# activation = 'tanh'
activation = 'relu'

x = tf.random.uniform(shape=(1, 10))

dense = Dense(units=1, activation=activation)

y_tf = dense(x)
W, B = dense.get_weights()

# Manual
y_man = tf.linalg.matmul(x, W) + B
if activation == 'sigmoid':
    y_man = 1 / (1 + exp(-y_man))
elif activation == 'tanh':
    y_man = (exp(y_man) - exp(-y_man)) / (exp(y_man) + exp(-y_man))
elif activation == 'relu':
    y_man = maximum(y_man, 0)

print("Activation: ", activation)
print("y_tf: {}\n{}\n".format(y_tf.shape, y_tf.numpy()))
print("y_man: {}\n{}\n".format(y_man.shape, y_man.numpy()))


Activation:  relu
y_tf: (1, 1)
[[0.16721363]]

y_man: (1, 1)
[[0.16721363]]



## MiniBaches

Shape of Dense Layers

In [13]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

N, n_feature = 8, 10
x = tf.random.normal(shape=(N, n_feature))

dense = Dense(units=1, activation='relu')
y = dense(x)

W, B = dense.get_weights()

print("Shape of x: ", x.shape)
print("Shape of W: ", W.shape)
print("Shape of B: ", B.shape)

Shape of x:  (8, 10)
Shape of W:  (10, 1)
Shape of B:  (1,)


Output Calculations

In [16]:
import tensorflow as tf

from tensorflow.keras.layers import Dense
N, n_feature = 8, 10
x = tf.random.normal(shape=(N, n_feature))

dense = Dense(units=1, activation='sigmoid')
y_tf = dense(x)

W, B = dense.get_weights()

y_man = tf.linalg.matmul(x, W) + B
y_man = 1 / ( 1 + tf.math.exp(-y_man))

print("Output(Tensorflow) : \n", y_tf.numpy())
print("Output(Manual) : \n", y_man.numpy())

Output(Tensorflow) : 
 [[0.44454572]
 [0.81287575]
 [0.54919004]
 [0.1762056 ]
 [0.4520619 ]
 [0.81538916]
 [0.7858276 ]
 [0.15387362]]
Output(Manual) : 
 [[0.44454572]
 [0.8128757 ]
 [0.54919004]
 [0.17620559]
 [0.4520619 ]
 [0.81538916]
 [0.7858276 ]
 [0.15387362]]
