### Softmax Layers

IO of Softmax

In [27]:
import tensorflow as tf

from tensorflow.keras.layers import Activation

logit = tf.random.uniform(shape=(2, 5), minval=-10, maxval=10)

softmax_value = Activation('softmax')(logit)
softmax_sum = tf.reduce_sum(softmax_value, axis=1)

print("Logits: \n", logit.numpy())
print("Probabilities: \n", softmax_value.numpy())
print("Sum of softmax values: \n", softmax_sum)

Logits: 
 [[-0.34876347  5.144372   -8.719044    1.7445545  -8.431608  ]
 [-3.7643647   5.5764627  -6.126721   -3.2601929   1.0130262 ]]
Probabilities: 
 [[3.9662030e-03 9.6385872e-01 9.1877342e-07 3.2172989e-02 1.2247293e-06]
 [8.6840373e-05 9.8944515e-01 8.1801918e-06 1.4377420e-04 1.0316120e-02]]
Sum of softmax values: 
 tf.Tensor([1. 1.], shape=(2,), dtype=float32)


Softmax in Dense Layers

In [28]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

logit = tf.random.uniform(shape=(8, 5), minval=-10, maxval=10)
dense = Dense(units=8, activation='softmax')

Y = dense(logit)
print(tf.reduce_sum(Y, axis=1))

tf.Tensor(
[1.         0.99999994 1.0000001  1.0000001  1.         1.0000001
 1.         1.        ], shape=(8,), dtype=float32)


### Multi-class Classifiers

Multi-class Classifiers

In [30]:
import tensorflow as tf

from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense

class TestModel(Model):
  def __init__(self):
    super(TestModel, self).__init__()

    self.dense1 = Dense(units=8, activation='relu')
    self.dense2 = Dense(units=5, activation='relu')
    self.dense3 = Dense(units=3, activation='softmax')

  def call(self, X):
    print("X: {}\n{}\n".format(X.shape, X.numpy()))

    X = self.dense1(X)
    print("A1: {}\n{}\n".format(X.shape, X.numpy()))

    X = self.dense2(X)
    print("A2: {}\n{}\n".format(X.shape, X.numpy()))

    X = self.dense3(X)
    print("Y: {}\n{}\n".format(X.shape, X.numpy()))
    print("Sum of vectors: {}\n".format(tf.reduce_sum(X, axis=1)))

model = TestModel()

X = tf.random.uniform(shape=(8, 5), minval=-10, maxval=10)
Y = model(X)

X: (8, 5)
[[-8.201981    1.671524   -0.46222687  9.716465    2.087407  ]
 [-7.3094225  -4.9207926  -6.582999    1.5219164  -8.129318  ]
 [ 2.723546   -5.916815    4.400051   -2.5845933   7.6256714 ]
 [ 5.6206083   3.6030054  -3.527441    7.3707275   7.1644783 ]
 [-7.524917    4.624426   -5.7665896  -1.5585213  -9.394571  ]
 [ 8.461935    0.31860352 -1.89291     3.6043854   9.5667305 ]
 [-5.969956   -2.9234695  -2.3770976   8.4966545   8.088036  ]
 [ 0.08798122  7.6674957   3.1443644   3.1177378   8.962845  ]]

A1: (8, 8)
[[ 8.151453    0.10897056  1.5550566   0.          6.6882143   0.
   0.          0.        ]
 [ 8.527092    0.          0.0501688   0.          5.9213457   0.
   1.6189634   0.        ]
 [ 0.          2.8658216   0.          0.          0.          0.01692989
   0.          4.598309  ]
 [ 0.77932113  0.24279076  9.9204855   6.356824    0.          4.1581426
   0.79321325  3.335121  ]
 [12.304554    0.          2.0245116   0.02350993  2.8432343   0.
   5.443017    0.   